-- =========================================================
-- PPID DIGITAL
-- Migration 0001
-- =========================================================


-- =========================================================
-- 1. TABLE PROFILES
-- =========================================================

create table public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    nama text not null,
    nik text,
    email text,
    telepon text,
    role text not null default 'pemohon'
        check (role in ('pemohon', 'admin')),
    created_at timestamptz not null default now()
);


-- =========================================================
-- 2. TABLE PERMOHONAN
-- =========================================================

create table public.permohonan (
    id bigint generated by default as identity primary key,

    user_id uuid not null
        references public.profiles(id)
        on delete cascade,

    jenis_informasi text not null,

    deskripsi text not null,

    cara_memperoleh text,

    status text not null default 'diajukan'
        check (
            status in (
                'diajukan',
                'diproses',
                'dijawab',
                'ditolak'
            )
        ),

    jawaban_admin text,

    deadline_awal date,

    diperpanjang boolean not null default false,

    alasan_perpanjangan text,

    deadline_akhir date,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now()
);


-- =========================================================
-- 3. TABLE KONTEN LANDING
-- =========================================================

create table public.konten_landing (
    id bigint generated by default as identity primary key,

    section_key text not null unique,

    judul text not null,

    isi_teks text,

    link_drive text,

    updated_by uuid
        references public.profiles(id)
        on delete set null,

    updated_at timestamptz not null default now()
);

-- =========================================================
-- 4. ENABLE ROW LEVEL SECURITY
-- =========================================================

alter table public.profiles enable row level security;

alter table public.permohonan enable row level security;

alter table public.konten_landing enable row level security;

-- =========================================================
-- 5. RLS PROFILES
-- =========================================================

create policy "user lihat profil sendiri"
on public.profiles
for select
using (
    auth.uid() = id
);

create policy "user edit profil sendiri"
on public.profiles
for update
using (
    auth.uid() = id
);

-- =========================================================
-- 6. RLS PERMOHONAN - PEMOHON
-- =========================================================

create policy "user lihat permohonan sendiri"
on public.permohonan
for select
using (
    auth.uid() = user_id
);

create policy "user insert permohonan sendiri"
on public.permohonan
for insert
with check (
    auth.uid() = user_id
);

-- =========================================================
-- 7. RLS PERMOHONAN - ADMIN
-- =========================================================

create policy "admin lihat semua permohonan"
on public.permohonan
for select
using (
    exists (
        select 1
        from public.profiles
        where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
);

create policy "admin update semua permohonan"
on public.permohonan
for update
using (
    exists (
        select 1
        from public.profiles
        where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
);

-- =========================================================
-- 8. RLS KONTEN LANDING
-- =========================================================

create policy "publik baca konten landing"
on public.konten_landing
for select
using (true);

create policy "admin insert konten landing"
on public.konten_landing
for insert
with check (
    exists (
        select 1
        from public.profiles
        where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
);

create policy "admin update konten landing"
on public.konten_landing
for update
using (
    exists (
        select 1
        from public.profiles
        where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
);

create policy "admin delete konten landing"
on public.konten_landing
for delete
using (
    exists (
        select 1
        from public.profiles
        where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
);

-- =========================================================
-- 9. INDEX
-- =========================================================

create index idx_permohonan_user_id
on public.permohonan(user_id);

create index idx_permohonan_status
on public.permohonan(status);

create index idx_permohonan_created_at
on public.permohonan(created_at);

create index idx_konten_landing_section_key
on public.konten_landing(section_key);

-- =========================================================
-- 10. FUNCTION AUTO CREATE PROFILE
-- =========================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (
        id,
        nama,
        nik,
        email,
        telepon,
        role
    )
    values (
        new.id,
        coalesce(
            new.raw_user_meta_data ->> 'nama',
            new.raw_user_meta_data ->> 'name',
            ''
        ),
        new.raw_user_meta_data ->> 'nik',
        new.email,
        coalesce(
            new.raw_user_meta_data ->> 'telepon',
            new.raw_user_meta_data ->> 'no_hp',
            ''
        ),
        coalesce(
            new.raw_user_meta_data ->> 'role',
            'pemohon'
        )
    );

    return new;
end;
$$;

-- =========================================================
-- 11. TRIGGER AUTO CREATE PROFILE
-- =========================================================

create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

