-- =========================================================
-- PPID DIGITAL
-- Migration 0001 (Idempotent / Safe Re-run)
-- =========================================================


-- =========================================================
-- 1. TABLE PROFILES
-- =========================================================

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    nama text not null,
    nik text,
    email text,
    telepon text,
    role text not null default 'pemohon'
        check (role in ('pemohon', 'admin')),
    created_at timestamptz not null default now()
);


-- =========================================================
-- 2. TABLE PERMOHONAN
-- =========================================================

create table if not exists public.permohonan (
    id bigint generated by default as identity primary key,

    user_id uuid not null
        references public.profiles(id)
        on delete cascade,

    jenis_informasi text not null,

    deskripsi text not null,

    cara_memperoleh text,

    status text not null default 'diajukan'
        check (
            status in (
                'diajukan',
                'diproses',
                'dijawab',
                'ditolak'
            )
        ),

    jawaban_admin text,

    deadline_awal date,

    diperpanjang boolean not null default false,

    alasan_perpanjangan text,

    deadline_akhir date,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now()
);


-- =========================================================
-- 3. TABLE KONTEN LANDING
-- =========================================================

create table if not exists public.konten_landing (
    id bigint generated by default as identity primary key,

    section_key text not null unique,

    judul text not null,

    isi_teks text,

    link_drive text,

    updated_by uuid
        references public.profiles(id)
        on delete set null,

    updated_at timestamptz not null default now()
);

-- Seed awal konten landing jika belum ada
insert into public.konten_landing (section_key, judul, isi_teks)
values 
  ('berkala', 'Informasi Berkala', 'Informasi yang diperbarui dan diumumkan secara rutin berkala oleh PPID CIKASDA.'),
  ('serta_merta', 'Informasi Serta Merta', 'Informasi penting yang menyangkut hajat hidup orang banyak dan ketertiban umum.'),
  ('setiap_saat', 'Informasi Setiap Saat', 'Informasi publik yang wajib disediakan dan dapat diakses kapan saja oleh pemohon.'),
  ('dikecualikan', 'Informasi Dikecualikan', 'Daftar informasi yang bersifat rahasia sesuai ketentuan regulasi dan undang-undang.')
on conflict (section_key) do nothing;

-- =========================================================
-- 3b. TABLE DOKUMEN PUBLIK
-- =========================================================

create table if not exists public.dokumen_publik (
    id bigint generated by default as identity primary key,
    kategori_key text not null references public.konten_landing(section_key) on delete cascade on update cascade,
    nama_dokumen text not null,
    file_url text not null,
    uploaded_by uuid references public.profiles(id) on delete set null,
    created_at timestamptz not null default now()
);

-- =========================================================
-- 4. ENABLE ROW LEVEL SECURITY
-- =========================================================

alter table public.profiles enable row level security;
alter table public.permohonan enable row level security;
alter table public.konten_landing enable row level security;
alter table public.dokumen_publik enable row level security;

-- =========================================================
-- 5. RLS PROFILES
-- =========================================================

drop policy if exists "user lihat profil sendiri" on public.profiles;
create policy "user lihat profil sendiri"
on public.profiles
for select
using (
    auth.uid() = id
);

-- FUNCTION: Cek apakah user adalah admin (Bypass RLS untuk mencegah infinite recursion)
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

drop policy if exists "admin lihat semua profil" on public.profiles;
create policy "admin lihat semua profil"
on public.profiles
for select
using ( public.is_admin() );

drop policy if exists "user insert profil sendiri" on public.profiles;
create policy "user insert profil sendiri"
on public.profiles
for insert
with check (
    auth.uid() = id
);

drop policy if exists "user edit profil sendiri" on public.profiles;
create policy "user edit profil sendiri"
on public.profiles
for update
using (
    auth.uid() = id
);

-- =========================================================
-- 6. RLS PERMOHONAN - PEMOHON
-- =========================================================

drop policy if exists "user lihat permohonan sendiri" on public.permohonan;
create policy "user lihat permohonan sendiri"
on public.permohonan
for select
using (
    auth.uid() = user_id
);

drop policy if exists "user insert permohonan sendiri" on public.permohonan;
create policy "user insert permohonan sendiri"
on public.permohonan
for insert
with check (
    auth.uid() = user_id
);

-- =========================================================
-- 7. RLS PERMOHONAN - ADMIN
-- =========================================================

drop policy if exists "admin lihat semua permohonan" on public.permohonan;
create policy "admin lihat semua permohonan"
on public.permohonan
for select
using ( public.is_admin() );

drop policy if exists "admin update semua permohonan" on public.permohonan;
create policy "admin update semua permohonan"
on public.permohonan
for update
using ( public.is_admin() );

-- =========================================================
-- 8. RLS KONTEN LANDING
-- =========================================================

drop policy if exists "publik baca konten landing" on public.konten_landing;
create policy "publik baca konten landing"
on public.konten_landing
for select
using (true);

drop policy if exists "admin insert konten landing" on public.konten_landing;
create policy "admin insert konten landing"
on public.konten_landing
for insert
with check ( public.is_admin() );

drop policy if exists "admin update konten landing" on public.konten_landing;
create policy "admin update konten landing"
on public.konten_landing
for update
using ( public.is_admin() );

drop policy if exists "admin delete konten landing" on public.konten_landing;
create policy "admin delete konten landing"
on public.konten_landing
for delete
using ( public.is_admin() );

-- =========================================================
-- 8b. RLS DOKUMEN PUBLIK
-- =========================================================

drop policy if exists "publik baca dokumen publik" on public.dokumen_publik;
create policy "publik baca dokumen publik"
on public.dokumen_publik
for select
using (true);

drop policy if exists "admin insert dokumen publik" on public.dokumen_publik;
create policy "admin insert dokumen publik"
on public.dokumen_publik
for insert
with check ( public.is_admin() );

drop policy if exists "admin update dokumen publik" on public.dokumen_publik;
create policy "admin update dokumen publik"
on public.dokumen_publik
for update
using ( public.is_admin() );

drop policy if exists "admin delete dokumen publik" on public.dokumen_publik;
create policy "admin delete dokumen publik"
on public.dokumen_publik
for delete
using ( public.is_admin() );

-- =========================================================
-- 9. INDEX
-- =========================================================

create index if not exists idx_permohonan_user_id
on public.permohonan(user_id);

create index if not exists idx_permohonan_status
on public.permohonan(status);

create index if not exists idx_permohonan_created_at
on public.permohonan(created_at);

create index if not exists idx_konten_landing_section_key
on public.konten_landing(section_key);

-- =========================================================
-- 10. FUNCTION AUTO CREATE PROFILE
-- =========================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (
        id,
        nama,
        nik,
        email,
        telepon,
        role
    )
    values (
        new.id,
        coalesce(
            new.raw_user_meta_data ->> 'nama',
            new.raw_user_meta_data ->> 'name',
            ''
        ),
        new.raw_user_meta_data ->> 'nik',
        new.email,
        coalesce(
            new.raw_user_meta_data ->> 'telepon',
            new.raw_user_meta_data ->> 'no_hp',
            ''
        ),
        coalesce(
            new.raw_user_meta_data ->> 'role',
            'pemohon'
        )
    )
    on conflict (id) do nothing;

    return new;
end;
$$;

-- =========================================================
-- 11. TRIGGER AUTO CREATE PROFILE
-- =========================================================

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row
execute function public.handle_new_user();

