-- =========================================================
-- PPID DIGITAL
-- Migration 0002: Daftar Informasi Publik Matrix CMS
-- =========================================================

-- 1. Tabel Header / Kategori Tabel Daftar Informasi Publik
create table if not exists public.daftar_informasi_tabel (
    id bigint generated by default as identity primary key,
    judul text not null,
    deskripsi text default 'Tahun 2022 - 2026',
    action_type text not null default 'unduh' check (action_type in ('unduh', 'klik')),
    urutan integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- 2. Tabel Baris Data & Tautan Tahun
create table if not exists public.daftar_informasi_item (
    id bigint generated by default as identity primary key,
    tabel_id bigint not null references public.daftar_informasi_tabel(id) on delete cascade,
    nama text not null,
    links jsonb not null default '{}'::jsonb, -- contoh: {"2022": "#", "2023": "https://...", ...}
    urutan integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Index untuk mempercepat query tabel dan urutan
create index if not exists idx_daftar_informasi_tabel_urutan on public.daftar_informasi_tabel(urutan, id);
create index if not exists idx_daftar_informasi_item_tabel on public.daftar_informasi_item(tabel_id, urutan, id);

-- 3. Row Level Security (RLS)
alter table public.daftar_informasi_tabel enable row level security;
alter table public.daftar_informasi_item enable row level security;

-- Kebijakan Pembacaan Publik (Anonim & Terotentikasi)
drop policy if exists "publik lihat daftar informasi tabel" on public.daftar_informasi_tabel;
create policy "publik lihat daftar informasi tabel"
on public.daftar_informasi_tabel
for select
using (true);

drop policy if exists "publik lihat daftar informasi item" on public.daftar_informasi_item;
create policy "publik lihat daftar informasi item"
on public.daftar_informasi_item
for select
using (true);

-- Kebijakan Pengelolaan Admin (Insert, Update, Delete)
drop policy if exists "admin kelola daftar informasi tabel" on public.daftar_informasi_tabel;
create policy "admin kelola daftar informasi tabel"
on public.daftar_informasi_tabel
for all
using (public.is_admin());

drop policy if exists "admin kelola daftar informasi item" on public.daftar_informasi_item;
create policy "admin kelola daftar informasi item"
on public.daftar_informasi_item
for all
using (public.is_admin());
