-- =========================================================
-- PPID DIGITAL
-- Migration 0003: Email Notification Templates CMS
-- =========================================================

-- 1. Table Email Templates
create table if not exists public.email_templates (
    id bigint generated by default as identity primary key,
    template_key text not null unique,
    nama_template text not null,
    target_penerima text not null check (target_penerima in ('admin', 'pemohon')),
    subjek text not null,
    badge_label text not null default 'Pemberitahuan Resmi',
    judul_heading text not null,
    pesan_pembuka text not null,
    pesan_penutup text not null default '',
    cta_label text not null default 'Lihat Rincian di Portal',
    updated_at timestamptz not null default now(),
    updated_by uuid references public.profiles(id) on delete set null
);

-- Index template_key
create index if not exists idx_email_templates_key on public.email_templates(template_key);

-- 2. Row Level Security (RLS)
alter table public.email_templates enable row level security;

-- Kebijakan Baca: Semua role terotentikasi & sistem dapat membaca template
drop policy if exists "publik dan sistem baca template email" on public.email_templates;
create policy "publik dan sistem baca template email"
on public.email_templates
for select
using (true);

-- Kebijakan Kelola: Hanya Admin yang dapat memperbarui template
drop policy if exists "admin kelola template email" on public.email_templates;
create policy "admin kelola template email"
on public.email_templates
for all
using (
  exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
    and profiles.role = 'admin'
  )
);

-- 3. Seed Awal 6 Template Resmi PPID CIKASDA Sulteng
insert into public.email_templates (
    template_key,
    nama_template,
    target_penerima,
    subjek,
    badge_label,
    judul_heading,
    pesan_pembuka,
    pesan_penutup,
    cta_label
)
values 
(
  'pengajuan_baru_admin',
  'Notifikasi Permohonan Baru (Petugas PPID)',
  'admin',
  '[PPID CIKASDA] Permohonan Informasi Publik Baru Masuk (#{{id}})',
  'Pemberitahuan Sistem',
  'Permohonan Informasi Baru Telah Diajukan',
  'Terdapat pengajuan permohonan informasi publik baru dari masyarakat yang memerlukan verifikasi dan tindak lanjut dari Petugas PPID Dinas Cipta Karya dan Sumber Daya Air Provinsi Sulawesi Tengah.',
  'Mohon segera lakukan verifikasi kelengkapan berkas pemohon dan tindak lanjuti sesuai ketentuan batas waktu layanan (SLA).',
  'Buka Admin Console'
),
(
  'pengajuan_baru_pemohon',
  'Tanda Terima Pengajuan (Pemohon)',
  'pemohon',
  '[PPID CIKASDA] Tanda Terima Pengajuan Permohonan Informasi (#{{id}})',
  'Tanda Terima Resmi',
  'Tanda Terima Registrasi Permohonan Informasi',
  'Yth. Sdr/i. {{nama}}, permohonan informasi publik Anda telah berhasil kami terima dan diregistrasikan ke dalam Sistem PPID Digital Dinas Cipta Karya dan Sumber Daya Air Provinsi Sulawesi Tengah.',
  'Permohonan Anda akan ditindaklanjuti oleh petugas PPID sesuai ketentuan Standar Layanan Informasi Publik. Anda dapat memantau perkembangan status permohonan secara berkala melalui portal PPID.',
  'Lihat Status Permohonan'
),
(
  'status_diproses',
  'Pemberitahuan Berkas Diproses (Pemohon)',
  'pemohon',
  '[PPID CIKASDA] Permohonan Informasi #{{id}} Sedang Diproses',
  'Pembaruan Status',
  'Permohonan Sedang Dalam Proses Penanganan',
  'Yth. Sdr/i. {{nama}}, kami informasikan bahwa berkas permohonan informasi publik Anda telah diverifikasi dan saat ini sedang dalam proses penanganan oleh unit kerja terkait pada Dinas CIKASDA Provinsi Sulawesi Tengah.',
  'Tim teknis dan PPID Pelaksana sedang melakukan koordinasi dan penyiapan dokumen yang Anda butuhkan. Kami akan mengabarkan kembali segera setelah tanggapan resmi disetujui.',
  'Lihat Status Permohonan'
),
(
  'jawaban_admin',
  'Tanggapan / Jawaban Resmi (Pemohon)',
  'pemohon',
  '[PPID CIKASDA] Tanggapan Resmi Permohonan Informasi #{{id}}',
  'Keputusan Resmi',
  'Tanggapan Resmi Permohonan Informasi #{{id}}',
  'Yth. Sdr/i. {{nama}}, PPID Dinas Cipta Karya dan Sumber Daya Air Provinsi Sulawesi Tengah telah menerbitkan tanggapan resmi atas permohonan informasi publik Anda.',
  'Apabila informasi yang diberikan memerlukan dokumen fisik atau verifikasi tambahan, Anda dapat mendatangi meja layanan PPID Dinas CIKASDA Provinsi Sulawesi Tengah pada jam kerja operasional.',
  'Buka Rincian & Unduh Jawaban'
),
(
  'perpanjangan_sla',
  'Pemberitahuan Perpanjangan Waktu Layanan (Pemohon)',
  'pemohon',
  '[PPID CIKASDA] Perpanjangan Batas Waktu Layanan Informasi #{{id}}',
  'Pemberitahuan SLA',
  'Pemberitahuan Perpanjangan Waktu Layanan (+7 Hari Kerja)',
  'Yth. Sdr/i. {{nama}}, berdasarkan Pasal 22 ayat (7) Undang-Undang Nomor 14 Tahun 2008 tentang Keterbukaan Informasi Publik, kami memberitahukan bahwa proses pemenuhan permohonan informasi Anda memerlukan perpanjangan waktu kerja.',
  'Kami berkomitmen untuk menyelesaikan permohonan Anda selambat-lambatnya pada tanggal batas waktu akhir di atas. Terima kasih atas pengertian dan kerja sama Anda.',
  'Periksa Rincian Permohonan'
),
(
  'penolakan',
  'Pemberitahuan Penolakan Permohonan (Pemohon)',
  'pemohon',
  '[PPID CIKASDA] Pemberitahuan Penolakan Permohonan Informasi #{{id}}',
  'Pemberitahuan Penolakan',
  'Pemberitahuan Penolakan Permohonan Informasi',
  'Yth. Sdr/i. {{nama}}, sehubungan dengan permohonan informasi publik yang Anda ajukan, kami menyampaikan bahwa permohonan tersebut tidak dapat dipenuhi dengan rincian alasan pertimbangan sebagai berikut:',
  'Sesuai dengan peraturan perundang-undangan yang berlaku, apabila Anda merasa keberatan atas penolakan ini, Anda berhak mengajukan Surat Keberatan melalui portal PPID paling lambat 30 (tiga puluh) hari kerja sejak diterimanya pemberitahuan ini.',
  'Lihat Keputusan Penolakan'
)
on conflict (template_key) do nothing;
