-- =========================================================
-- PPID DIGITAL - DINAS CIKASDA PROV. SULTENG
-- Migration 0004: Survei Kepuasan Masyarakat (IKM)
-- Standar PermenPAN-RB No. 14 Tahun 2017 & Standar Monev KI
-- =========================================================

-- 1. Buat Tabel Survei Kepuasan
create table if not exists public.survei_kepuasan (
    id bigint generated by default as identity primary key,
    
    -- Relasi One-to-One ke Permohonan (1 permohonan hanya bisa dinilai 1 kali)
    permohonan_id bigint not null unique
        references public.permohonan(id)
        on delete cascade,

    -- Relasi ke Pemohon yang mengisi survei
    user_id uuid not null
        references public.profiles(id)
        on delete cascade,

    -- Skor Utama (Skala Likert 1 s.d. 5)
    skor_keseluruhan integer not null
        check (skor_keseluruhan between 1 and 5),

    -- Unsur Pelayanan IKM Spesifik (PermenPAN-RB No. 14/2017)
    kecepatan_layanan integer not null
        check (kecepatan_layanan between 1 and 5),

    kesesuaian_informasi integer not null
        check (kesesuaian_informasi between 1 and 5),

    kemudahan_prosedur integer not null
        check (kemudahan_prosedur between 1 and 5),

    -- Umpan Balik Kualitatif (Kritik, Saran & Aspirasi)
    kritik_saran text,

    created_at timestamptz not null default now()
);

-- 2. Index Pencarian & Performa Agregasi Laporan
create index if not exists idx_survei_permohonan on public.survei_kepuasan(permohonan_id);
create index if not exists idx_survei_user on public.survei_kepuasan(user_id);
create index if not exists idx_survei_created on public.survei_kepuasan(created_at desc);

-- 3. Row Level Security (RLS)
alter table public.survei_kepuasan enable row level security;

-- Kebijakan Baca Pemohon: Pemohon hanya dapat melihat survei yang telah diisinya sendiri
drop policy if exists "pemohon lihat survei sendiri" on public.survei_kepuasan;
create policy "pemohon lihat survei sendiri"
on public.survei_kepuasan
for select
using ( auth.uid() = user_id );

-- Kebijakan Input Pemohon:
-- Pemohon hanya dapat mengisi survei untuk permohonan miliknya sendiri yang sudah berstatus 'dijawab'
drop policy if exists "pemohon isi survei sendiri" on public.survei_kepuasan;
create policy "pemohon isi survei sendiri"
on public.survei_kepuasan
for insert
with check (
    auth.uid() = user_id
    and exists (
        select 1 from public.permohonan
        where permohonan.id = permohonan_id
        and permohonan.user_id = auth.uid()
        and permohonan.status = 'dijawab'
    )
);

-- Kebijakan Admin: Petugas Admin PPID dapat melihat dan mengelola semua data survei untuk rekapitulasi IKM
drop policy if exists "admin kelola survei" on public.survei_kepuasan;
create policy "admin kelola survei"
on public.survei_kepuasan
for all
using ( public.is_admin() )
with check ( public.is_admin() );
